---
- hosts: localhost
  vars: 
    continents:
    - Africa
    - Asia
    - South America
    - North America
    - Europe
  tasks:
  - name: Ansible list variable example
    debug:
      msg: "{{ continents [1] }}" 
